#!/usr/bin/php
<?php

function app_path($path=''){
	return APP_PATH . $path;
}

function libs($path=''){
	return app_path('/vendor/crystalphp/framework/src/Crystal' . $path);
}

define('APP_PATH', __DIR__);
include APP_PATH . '/vendor/autoload.php';

$app = new \Crystal\Console\Kernel;
echo $app->handle($argv);
